#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap          12

bspc config bottom_padding      68
bspc config up_padding          68
bspc config right_padding       68
bspc config left_padding        68

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a \* rectangle 800x600+0+0 center=true state=floating
# bspc rule -a Brave-browser rectangle 1366x768+0+0 state=pseudo_tiled
